-- Importacion de usuarios EF
-- Fecha: 2026-05-14
-- Contrasena por defecto: Flexcon2026

INSERT INTO `users` (`name`, `last_name`, `account`, `employee_number`, `position`, `birth_date`, `entry_date`, `comments`, `active`, `area_id`, `shift_id`, `email`, `email_verified_at`, `password`, `remember_token`, `created_at`, `updated_at`, `deleted_at`) VALUES ('Ana', 'Romero', 'aromero', NULL, 'Gerente de Calidad', '1990-05-15', '2024-01-10', NULL, 1, 9, NULL, 'aromero@ensamblesformula.com', NULL, '$2y$12$Gm9PI7FQLKbuLaWqF3hYNOcRs6E/z1KE0Cg5FpIbR3KVkZMYN4LMi', NULL, '2026-01-01 08:00:00', '2026-01-01 08:00:00', NULL);
INSERT INTO `users` (`name`, `last_name`, `account`, `employee_number`, `position`, `birth_date`, `entry_date`, `comments`, `active`, `area_id`, `shift_id`, `email`, `email_verified_at`, `password`, `remember_token`, `created_at`, `updated_at`, `deleted_at`) VALUES ('Lorena', 'Adams', 'ladams', NULL, 'Auxiliar de Calidad', '1988-03-22', '2023-06-01', NULL, 1, 9, NULL, 'ladams@ensamblesformula.com', NULL, '$2y$12$Gm9PI7FQLKbuLaWqF3hYNOcRs6E/z1KE0Cg5FpIbR3KVkZMYN4LMi', NULL, '2026-01-01 08:00:00', '2026-01-01 08:00:00', NULL);
INSERT INTO `users` (`name`, `last_name`, `account`, `employee_number`, `position`, `birth_date`, `entry_date`, `comments`, `active`, `area_id`, `shift_id`, `email`, `email_verified_at`, `password`, `remember_token`, `created_at`, `updated_at`, `deleted_at`) VALUES ('Angeles', 'Angeles', 'creyes', NULL, 'Inspector de Calidad', '1985-12-10', '2022-09-15', NULL, 1, 9, NULL, 'creyes@ensamblesformula.com', NULL, '$2y$12$Gm9PI7FQLKbuLaWqF3hYNOcRs6E/z1KE0Cg5FpIbR3KVkZMYN4LMi', NULL, '2026-01-01 08:00:00', '2026-01-01 08:00:00', NULL);
INSERT INTO `users` (`name`, `last_name`, `account`, `employee_number`, `position`, `birth_date`, `entry_date`, `comments`, `active`, `area_id`, `shift_id`, `email`, `email_verified_at`, `password`, `remember_token`, `created_at`, `updated_at`, `deleted_at`) VALUES ('Raquel', 'Vasquez', 'rvasquez', NULL, 'Inspector de Calidad', NULL, NULL, NULL, 1, 9, NULL, 'rvasquez@ensamblesformula.com', NULL, '$2y$12$Gm9PI7FQLKbuLaWqF3hYNOcRs6E/z1KE0Cg5FpIbR3KVkZMYN4LMi', NULL, '2026-01-01 08:00:00', '2026-01-01 08:00:00', NULL);
INSERT INTO `users` (`name`, `last_name`, `account`, `employee_number`, `position`, `birth_date`, `entry_date`, `comments`, `active`, `area_id`, `shift_id`, `email`, `email_verified_at`, `password`, `remember_token`, `created_at`, `updated_at`, `deleted_at`) VALUES ('Julissa', 'Larios', 'jlarios', NULL, 'Inspector de Calidad', NULL, NULL, NULL, 1, 9, NULL, 'jlarios@ensamblesformula.com', NULL, '$2y$12$Gm9PI7FQLKbuLaWqF3hYNOcRs6E/z1KE0Cg5FpIbR3KVkZMYN4LMi', NULL, '2026-01-01 08:00:00', '2026-01-01 08:00:00', NULL);
INSERT INTO `users` (`name`, `last_name`, `account`, `employee_number`, `position`, `birth_date`, `entry_date`, `comments`, `active`, `area_id`, `shift_id`, `email`, `email_verified_at`, `password`, `remember_token`, `created_at`, `updated_at`, `deleted_at`) VALUES ('Angel', 'Gonzalez', 'agonzalez', NULL, 'Inspector de Calidad', NULL, NULL, NULL, 1, 9, NULL, 'agonzalez@ensamblesformula.com', NULL, '$2y$12$Gm9PI7FQLKbuLaWqF3hYNOcRs6E/z1KE0Cg5FpIbR3KVkZMYN4LMi', NULL, '2026-01-01 08:00:00', '2026-01-01 08:00:00', NULL);
INSERT INTO `users` (`name`, `last_name`, `account`, `employee_number`, `position`, `birth_date`, `entry_date`, `comments`, `active`, `area_id`, `shift_id`, `email`, `email_verified_at`, `password`, `remember_token`, `created_at`, `updated_at`, `deleted_at`) VALUES ('Martina', 'Romero', 'mromero', NULL, 'Inspector de Calidad', NULL, NULL, NULL, 1, 9, NULL, 'mromero@ensamblesformula.com', NULL, '$2y$12$Gm9PI7FQLKbuLaWqF3hYNOcRs6E/z1KE0Cg5FpIbR3KVkZMYN4LMi', NULL, '2026-01-01 08:00:00', '2026-01-01 08:00:00', NULL);
INSERT INTO `users` (`name`, `last_name`, `account`, `employee_number`, `position`, `birth_date`, `entry_date`, `comments`, `active`, `area_id`, `shift_id`, `email`, `email_verified_at`, `password`, `remember_token`, `created_at`, `updated_at`, `deleted_at`) VALUES ('Cinthia', 'Neri', 'cneri', NULL, 'Supervisor de Empaque', NULL, NULL, NULL, 1, 11, NULL, 'cneri@ensamblesformula.com', NULL, '$2y$12$Gm9PI7FQLKbuLaWqF3hYNOcRs6E/z1KE0Cg5FpIbR3KVkZMYN4LMi', NULL, '2026-01-01 08:00:00', '2026-01-01 08:00:00', NULL);
INSERT INTO `users` (`name`, `last_name`, `account`, `employee_number`, `position`, `birth_date`, `entry_date`, `comments`, `active`, `area_id`, `shift_id`, `email`, `email_verified_at`, `password`, `remember_token`, `created_at`, `updated_at`, `deleted_at`) VALUES ('Yarele', 'Olguin', 'ysalas', NULL, 'Auxiliar de Empaque', NULL, NULL, NULL, 1, 11, NULL, 'ysalas@ensamblesformula.com', NULL, '$2y$12$Gm9PI7FQLKbuLaWqF3hYNOcRs6E/z1KE0Cg5FpIbR3KVkZMYN4LMi', NULL, '2026-01-01 08:00:00', '2026-01-01 08:00:00', NULL);
INSERT INTO `users` (`name`, `last_name`, `account`, `employee_number`, `position`, `birth_date`, `entry_date`, `comments`, `active`, `area_id`, `shift_id`, `email`, `email_verified_at`, `password`, `remember_token`, `created_at`, `updated_at`, `deleted_at`) VALUES ('Juan', 'Gastelum', 'jgastelum', NULL, 'Gerente de Produccion', NULL, NULL, NULL, 1, NULL, NULL, 'jgastelum@ensamblesformula.com', NULL, '$2y$12$Gm9PI7FQLKbuLaWqF3hYNOcRs6E/z1KE0Cg5FpIbR3KVkZMYN4LMi', NULL, '2026-01-01 08:00:00', '2026-01-01 08:00:00', NULL);
INSERT INTO `users` (`name`, `last_name`, `account`, `employee_number`, `position`, `birth_date`, `entry_date`, `comments`, `active`, `area_id`, `shift_id`, `email`, `email_verified_at`, `password`, `remember_token`, `created_at`, `updated_at`, `deleted_at`) VALUES ('Bertha', 'Lopez', 'blopez', NULL, 'Supervisor de Produccion', NULL, NULL, NULL, 1, NULL, NULL, 'blopez@ensamblesformula.com', NULL, '$2y$12$Gm9PI7FQLKbuLaWqF3hYNOcRs6E/z1KE0Cg5FpIbR3KVkZMYN4LMi', NULL, '2026-01-01 08:00:00', '2026-01-01 08:00:00', NULL);
INSERT INTO `users` (`name`, `last_name`, `account`, `employee_number`, `position`, `birth_date`, `entry_date`, `comments`, `active`, `area_id`, `shift_id`, `email`, `email_verified_at`, `password`, `remember_token`, `created_at`, `updated_at`, `deleted_at`) VALUES ('Guadalupe', 'Holguien', 'aholguin', NULL, 'Auxiliar de Produccion', NULL, NULL, NULL, 1, NULL, NULL, 'aholguin@ensamblesformula.com', NULL, '$2y$12$Gm9PI7FQLKbuLaWqF3hYNOcRs6E/z1KE0Cg5FpIbR3KVkZMYN4LMi', NULL, '2026-01-01 08:00:00', '2026-01-01 08:00:00', NULL);
INSERT INTO `users` (`name`, `last_name`, `account`, `employee_number`, `position`, `birth_date`, `entry_date`, `comments`, `active`, `area_id`, `shift_id`, `email`, `email_verified_at`, `password`, `remember_token`, `created_at`, `updated_at`, `deleted_at`) VALUES ('Araceli', 'Bojorquez', 'abojorquez', NULL, 'Auxiliar de Produccion', NULL, NULL, NULL, 1, NULL, NULL, 'abojorquez@ensamblesformula.com', NULL, '$2y$12$Gm9PI7FQLKbuLaWqF3hYNOcRs6E/z1KE0Cg5FpIbR3KVkZMYN4LMi', NULL, '2026-01-01 08:00:00', '2026-01-01 08:00:00', NULL);
INSERT INTO `users` (`name`, `last_name`, `account`, `employee_number`, `position`, `birth_date`, `entry_date`, `comments`, `active`, `area_id`, `shift_id`, `email`, `email_verified_at`, `password`, `remember_token`, `created_at`, `updated_at`, `deleted_at`) VALUES ('Diana', 'Rivera', 'drivera', NULL, 'Especialista SGC', NULL, NULL, NULL, 1, 9, NULL, 'drivera@ensamblesformula.com', NULL, '$2y$12$Gm9PI7FQLKbuLaWqF3hYNOcRs6E/z1KE0Cg5FpIbR3KVkZMYN4LMi', NULL, '2026-01-01 08:00:00', '2026-01-01 08:00:00', NULL);
INSERT INTO `users` (`name`, `last_name`, `account`, `employee_number`, `position`, `birth_date`, `entry_date`, `comments`, `active`, `area_id`, `shift_id`, `email`, `email_verified_at`, `password`, `remember_token`, `created_at`, `updated_at`, `deleted_at`) VALUES ('Carmen', 'Ramirez', 'cramirez', NULL, 'Supervisor de Control de Materiales', NULL, NULL, NULL, 1, 5, NULL, 'cramirez@ensamblesformula.com', NULL, '$2y$12$Gm9PI7FQLKbuLaWqF3hYNOcRs6E/z1KE0Cg5FpIbR3KVkZMYN4LMi', NULL, '2026-01-01 08:00:00', '2026-01-01 08:00:00', NULL);
INSERT INTO `users` (`name`, `last_name`, `account`, `employee_number`, `position`, `birth_date`, `entry_date`, `comments`, `active`, `area_id`, `shift_id`, `email`, `email_verified_at`, `password`, `remember_token`, `created_at`, `updated_at`, `deleted_at`) VALUES ('Laura', 'Ramirez', 'lramirez', NULL, 'Auxiliar de Control de Materiales', NULL, NULL, NULL, 1, 5, NULL, 'lramirez@ensamblesformula.com', NULL, '$2y$12$Gm9PI7FQLKbuLaWqF3hYNOcRs6E/z1KE0Cg5FpIbR3KVkZMYN4LMi', NULL, '2026-01-01 08:00:00', '2026-01-01 08:00:00', NULL);
INSERT INTO `users` (`name`, `last_name`, `account`, `employee_number`, `position`, `birth_date`, `entry_date`, `comments`, `active`, `area_id`, `shift_id`, `email`, `email_verified_at`, `password`, `remember_token`, `created_at`, `updated_at`, `deleted_at`) VALUES ('Leonel', 'Cabrera', 'lcabrera', NULL, 'Auxiliar de Control de Materiales', NULL, NULL, NULL, 1, 5, NULL, 'lcabrera@ensamblesformula.com', NULL, '$2y$12$Gm9PI7FQLKbuLaWqF3hYNOcRs6E/z1KE0Cg5FpIbR3KVkZMYN4LMi', NULL, '2026-01-01 08:00:00', '2026-01-01 08:00:00', NULL);
INSERT INTO `users` (`name`, `last_name`, `account`, `employee_number`, `position`, `birth_date`, `entry_date`, `comments`, `active`, `area_id`, `shift_id`, `email`, `email_verified_at`, `password`, `remember_token`, `created_at`, `updated_at`, `deleted_at`) VALUES ('Karina', 'Lopez', 'klopez', NULL, 'Auxiliar de Control de Materiales', NULL, NULL, NULL, 1, 5, NULL, 'klopez@ensamblesformula.com', NULL, '$2y$12$Gm9PI7FQLKbuLaWqF3hYNOcRs6E/z1KE0Cg5FpIbR3KVkZMYN4LMi', NULL, '2026-01-01 08:00:00', '2026-01-01 08:00:00', NULL);
INSERT INTO `users` (`name`, `last_name`, `account`, `employee_number`, `position`, `birth_date`, `entry_date`, `comments`, `active`, `area_id`, `shift_id`, `email`, `email_verified_at`, `password`, `remember_token`, `created_at`, `updated_at`, `deleted_at`) VALUES ('Anhirah', 'Ramirez', 'aramirez', NULL, 'Admon y Recursos Humanos', NULL, NULL, NULL, 1, 12, NULL, 'aramirez@ensamblesformula.com', NULL, '$2y$12$Gm9PI7FQLKbuLaWqF3hYNOcRs6E/z1KE0Cg5FpIbR3KVkZMYN4LMi', NULL, '2026-01-01 08:00:00', '2026-01-01 08:00:00', NULL);
INSERT INTO `users` (`name`, `last_name`, `account`, `employee_number`, `position`, `birth_date`, `entry_date`, `comments`, `active`, `area_id`, `shift_id`, `email`, `email_verified_at`, `password`, `remember_token`, `created_at`, `updated_at`, `deleted_at`) VALUES ('Dahiana', 'de los Santos', 'dsantos', NULL, 'Auxiliar de Produccion', NULL, NULL, NULL, 1, NULL, NULL, 'dsantos@ensamblesformula.com', NULL, '$2y$12$Gm9PI7FQLKbuLaWqF3hYNOcRs6E/z1KE0Cg5FpIbR3KVkZMYN4LMi', NULL, '2026-01-01 08:00:00', '2026-01-01 08:00:00', NULL);
